// Rhyme suggestion utility — shared between write screen and DevPanel hint test
//
// VALIDATION NOTE: After every suggestRhymes() call whose result feeds a hint,
// run isValidRhymePair(word, rhyme) to cross-check the pair is genuine.
// This catches suffix-matching false positives (e.g. "roast" → "ast" → "last").

export const HINT_PHRASES: Array<(word: string, rhyme: string) => string> = [
  (w, r) => `Stuck? Run '${w}' into '${r}' — close that bar`,
  (w, r) => `OG says: bridge '${w}' with '${r}', make it land`,
  (w, r) => `'${w}' set it up. '${r}' brings it home.`,
  (w, r) => `Need a rhyme? '${w}' × '${r}' — that combo still fresh`,
  (w, r) => `Flip '${w}' on '${r}' — keep that pocket tight`,
  (w, r) => `Can't find the end? '${w}' lands nice on '${r}'`,
  (w, r) => `Hook for '${w}': try '${r}' to close it out`,
];

export function pickHintPhrase(word: string, rhyme: string): string {
  const fn = HINT_PHRASES[Math.floor(Math.random() * HINT_PHRASES.length)]!;
  return fn(word, rhyme);
}

export function suggestRhymes(word: string): string[] {
  const w = word.toLowerCase().replace(/[^a-z]/g, "");

  const wordBank: Record<string, string[]> = {
    // Original battle word bank
    neon:       ["on", "gone", "con", "spawn", "beyond", "upon", "respond"],
    ghost:      ["most", "coast", "toast", "host", "boast", "roast", "post"],
    throne:     ["bone", "stone", "alone", "tone", "phone", "zone", "clone"],
    velocity:   ["ferocity", "atrocity", "tenacity", "audacity", "curiosity", "animosity"],
    eclipse:    ["trips", "grips", "ships", "lips", "scripts", "crypts", "sips"],
    alchemy:    ["harmony", "symphony", "ceremony", "melody", "memory", "enemy"],
    fracture:   ["capture", "chapter", "laughter", "after", "rapture", "pastor"],
    labyrinth:  ["within", "discipline", "genuine", "medicine", "feminine", "begin"],
    voltage:    ["stage", "cage", "age", "rage", "engage", "rampage", "enrage"],
    paradox:    ["blocks", "rocks", "clocks", "knocks", "locks", "talks", "walks"],
    cipher:     ["fire", "desire", "inspire", "higher", "entire", "admire", "wire"],
    tempest:    ["best", "rest", "quest", "chest", "invest", "conquest", "protest"],
    venom:      ["phantom", "random", "seldom", "kingdom", "rhythm", "ransom", "wisdom"],
    prism:      ["rhythm", "wisdom", "phantom", "random", "kingdom", "blossom", "bottom"],
    reckoning:  ["beckoning", "threatening", "awakening", "happening", "questioning"],
    void:       ["destroyed", "employed", "annoyed", "deployed", "overjoyed", "avoid"],
    zenith:     ["beneath", "breathe", "seethe", "teeth", "wreath", "strength", "length"],
    ember:      ["remember", "December", "member", "surrender", "center", "render"],
    catalyst:   ["fatalist", "naturalist", "analyst", "finalist", "exist", "persist"],
    phantom:    ["random", "kingdom", "ransom", "venom", "rhythm", "wisdom", "prism"],
    sovereign:  ["governing", "hovering", "reckoning", "offering", "wandering"],
    vertigo:    ["echo", "tempo", "below", "shadow", "meadow", "flow", "bestow"],
    resonance:  ["dominance", "prominence", "renaissance", "tolerance", "dance", "chance"],
    horizon:    ["rising", "surprising", "disguising", "advising", "comprising", "arising"],
    infinite:   ["definite", "opposite", "sensitive", "passionate", "exquisite"],
    debris:     ["free", "me", "see", "key", "agree", "degree", "emcee"],
    legacy:     ["prophecy", "secrecy", "advocacy", "democracy", "accuracy", "intimacy"],
    crimson:    ["listen", "prison", "risen", "frozen", "chosen", "season", "reason"],
    mirage:     ["barrage", "massage", "collage", "garage", "corsage", "montage"],
    static:     ["automatic", "dramatic", "systematic", "traumatic", "charismatic", "frantic"],
    // Expanded
    apex:       ["complex", "reflex", "perplex", "specs", "checks", "decks", "wrecks"],
    abyss:      ["bliss", "kiss", "miss", "dismiss", "exist", "resist", "insist"],
    blaze:      ["gaze", "phase", "raise", "maze", "days", "daze", "amaze"],
    chrome:     ["home", "dome", "roam", "foam", "zone", "throne", "poem"],
    cosmos:     ["flows", "grows", "shows", "knows", "glows", "goes", "prose"],
    crown:      ["town", "down", "brown", "grown", "noun", "renown", "countdown"],
    dusk:       ["must", "trust", "gust", "dust", "disgust", "just", "crust"],
    depths:     ["breath", "death", "stealth", "health", "wealth", "felt", "dealt"],
    empire:     ["fire", "desire", "inspire", "higher", "entire", "admire", "wire"],
    exile:      ["style", "mile", "smile", "while", "file", "denial", "trial"],
    fate:       ["great", "wait", "state", "late", "weight", "create", "debate"],
    fever:      ["never", "forever", "clever", "endeavor", "together", "whether", "ether"],
    flame:      ["game", "name", "frame", "fame", "claim", "aim", "proclaim"],
    glory:      ["story", "morning", "warning", "boring", "roaring", "soaring", "pouring"],
    grave:      ["save", "brave", "wave", "cave", "slave", "crave", "engrave"],
    grind:      ["mind", "find", "kind", "blind", "behind", "refined", "defined"],
    hunger:     ["wonder", "thunder", "under", "blunder", "number", "plunder", "asunder"],
    icon:       ["on", "gone", "con", "upon", "beyond", "respond", "drawn"],
    karma:      ["armor", "farther", "harder", "garden", "pardon", "darken", "barren"],
    lava:       ["over", "sober", "soldier", "closure", "closer", "rover", "boulder"],
    marble:     ["sparkle", "dark", "mark", "spark", "stark", "embark", "remark"],
    mercury:    ["urgency", "currency", "certainly", "personally", "journey", "attorney"],
    myth:       ["strength", "length", "depth", "breath", "death", "stealth", "health"],
    omega:      ["mega", "begin", "within", "discipline", "genuine", "medicine", "feminine"],
    oracle:     ["tropical", "radical", "critical", "chemical", "medical", "miracle", "cynical"],
    pinnacle:   ["cynical", "miracle", "radical", "critical", "chemical", "magical", "physical"],
    plasma:     ["drama", "trauma", "panorama", "karma", "lava", "armor", "darker"],
    pulse:      ["results", "revolts", "faults", "vaults", "assault", "exalts", "halts"],
    reign:      ["pain", "rain", "brain", "chain", "gain", "train", "insane"],
    ritual:     ["spiritual", "individual", "visual", "mutual", "usual", "continual"],
    rush:       ["crush", "brush", "hush", "flush", "thrust", "gust", "must"],
    saga:       ["drama", "trauma", "karma", "armor", "harder", "farther", "garden"],
    silence:    ["violence", "science", "compliance", "reliance", "defiance", "alliance", "giants"],
    silver:     ["river", "deliver", "giver", "shiver", "quiver", "liver", "pillar"],
    specter:    ["vector", "sector", "lecture", "capture", "chapter", "laughter", "rapture"],
    spiral:     ["viral", "rival", "survival", "revival", "final", "trial", "denial"],
    storm:      ["warm", "form", "norm", "transform", "conform", "reform", "perform"],
    surge:      ["urge", "verge", "merge", "emerge", "submerge", "converge", "purge"],
    titan:      ["lighten", "frighten", "tighten", "brighten", "enlighten", "triton"],
    trial:      ["mile", "smile", "style", "while", "denial", "exile", "file"],
    twilight:   ["night", "fight", "right", "light", "might", "bright", "sight"],
    ultra:      ["culture", "vulture", "structure", "future", "suture", "sculpture", "rupture"],
    vortex:     ["complex", "reflex", "perplex", "checks", "decks", "wrecks", "specs"],
    weapon:     ["happen", "captain", "open", "token", "broken", "spoken", "woken"],
    witness:    ["fitness", "business", "thickness", "sickness", "swiftness", "richness"],
    wrath:      ["path", "math", "aftermath", "laugh", "graph", "craft"],
    zero:       ["hero", "stereo", "scenario", "area", "idea", "fear"],
    zeal:       ["feel", "real", "deal", "steel", "reveal", "appeal", "conceal"],
    nova:       ["over", "closure", "soldier", "sober", "rover", "boulder", "smolder"],
    chaos:      ["boss", "loss", "cross", "toss", "sauce", "across", "exhaust"],
    goat:       ["boat", "coat", "throat", "note", "vote", "float", "quote"],
    drift:      ["gift", "swift", "shift", "lift", "rift", "uplift", "adrift"],
    fury:       ["story", "glory", "morning", "boring", "roaring", "jury", "hurry"],
    grit:       ["split", "sit", "hit", "fit", "commit", "submit", "permit"],
    haze:       ["gaze", "phase", "blaze", "maze", "days", "daze", "amaze"],
    jade:       ["made", "shade", "blade", "trade", "fade", "parade", "evade"],
    kinetic:    ["magnetic", "pathetic", "athletic", "phonetic", "genetic", "frenetic", "synthetic"],
    lore:       ["more", "core", "floor", "soar", "explore", "restore", "implore"],
    monolith:   ["myth", "strength", "length", "breath", "depth", "health", "stealth"],
    nerve:      ["serve", "curve", "deserve", "reserve", "observe", "preserve", "swerve"],
    oblivion:   ["vision", "mission", "position", "decision", "precision", "collision", "revision"],
    pyre:       ["fire", "desire", "inspire", "higher", "entire", "admire", "wire"],
    quake:      ["break", "shake", "wake", "stake", "mistake", "awake", "forsake"],
    ruin:       ["through", "pursue", "renew", "debut", "review", "undo", "imbue"],
    shard:      ["hard", "guard", "scarred", "barred", "regard", "discard", "bombard"],
    terrain:    ["pain", "rain", "brain", "chain", "gain", "train", "insane"],
    undead:     ["head", "dread", "spread", "instead", "ahead", "thread", "said"],
    valor:      ["collar", "dollar", "holler", "scholar", "solar", "polar", "molar"],
    wraith:     ["faith", "eighth", "shape", "drape", "escape", "landscape"],
    xenon:      ["on", "gone", "con", "spawn", "beyond", "upon", "respond"],
    yield:      ["shield", "field", "wield", "healed", "revealed", "sealed", "appealed"],
    // Hip-hop / AAVE vocabulary
    drip:       ["grip", "trip", "flip", "tip", "skip", "rip", "chip"],
    flex:       ["complex", "reflex", "checks", "decks", "wrecks", "specs", "text"],
    vibe:       ["tribe", "describe", "prescribe", "bribe", "scribe", "thrive", "alive"],
    sauce:      ["loss", "cross", "boss", "toss", "across", "exhaust", "cost"],
    clout:      ["out", "shout", "doubt", "about", "throughout", "devout", "sprout"],
    heat:       ["street", "beat", "feat", "treat", "complete", "defeat", "concrete"],
    smoke:      ["spoke", "broke", "woke", "stroke", "invoke", "cloak", "choke"],
    spit:       ["split", "hit", "fit", "commit", "submit", "permit", "legit"],
    bars:       ["stars", "scars", "cars", "jars", "guitars", "memoirs", "bazaars"],
    dope:       ["hope", "cope", "rope", "scope", "quote", "wrote", "note"],
    raw:        ["saw", "draw", "flaw", "law", "jaw", "awe", "gnaw"],
    bounce:     ["ounce", "announce", "pronounce", "renounce", "pounce", "trounce"],
    murk:       ["work", "lurk", "quirk", "perk", "shirk", "irk", "jerk"],
    cold:       ["bold", "gold", "hold", "told", "fold", "unfold", "controlled"],
    plug:       ["drug", "shrug", "slug", "thug", "bug", "hug", "mug"],
    thug:       ["drug", "shrug", "slug", "plug", "bug", "hug", "mug"],
    trap:       ["map", "cap", "rap", "lap", "snap", "gap", "clap"],
    rap:        ["cap", "map", "trap", "lap", "snap", "gap", "clap"],
    slay:       ["way", "stay", "play", "say", "pray", "today", "display"],
    wave:       ["save", "brave", "cave", "slave", "crave", "engrave", "behave"],
    fly:        ["high", "sky", "cry", "try", "deny", "justify", "amplify"],
    fresh:      ["mesh", "flesh", "thresh", "enmesh", "refresh", "dress", "stress"],
    blessed:    ["stressed", "pressed", "confessed", "dressed", "expressed", "possessed"],
    gifted:     ["lifted", "shifted", "drifted", "shifted", "sifted", "gifted", "swifted"],
    real:       ["feel", "deal", "steel", "heal", "reveal", "appeal", "conceal"],
    street:     ["beat", "heat", "feat", "treat", "complete", "defeat", "concrete"],
    money:      ["honey", "funny", "sunny", "bunny", "runny", "journey", "attorney"],
    hustle:     ["muscle", "bustle", "tussle", "rustle", "puzzle", "muzzle"],
    shine:      ["divine", "fine", "vine", "mine", "design", "spine", "nine"],
    king:       ["ring", "sing", "bring", "spring", "swing", "sting", "thing"],
    queen:      ["seen", "mean", "clean", "between", "dream", "scheme", "extreme"],
    legend:     ["heaven", "seven", "eleven", "leaven", "threaten", "beckon", "reckoned"],
    // Common words that fall through to bad suffix matches without explicit entries
    roast:      ["most", "coast", "toast", "host", "boast", "ghost", "post"],
    mid:        ["bid", "did", "grid", "hid", "kid", "lid", "rid", "skid"],
    last:       ["fast", "past", "vast", "blast", "cast", "mast", "contrast"],
    fast:       ["last", "past", "vast", "blast", "cast", "mast", "contrast"],
    past:       ["last", "fast", "vast", "blast", "cast", "contrast", "vast"],
    night:      ["fight", "right", "light", "might", "bright", "sight", "tight"],
    day:        ["way", "stay", "play", "say", "pray", "display", "today"],
    mind:       ["find", "kind", "blind", "behind", "refined", "defined", "grind"],
    time:       ["rhyme", "climb", "prime", "lime", "sublime", "paradigm", "dime"],
    life:       ["knife", "strife", "wife", "rife", "drive", "alive", "thrive"],
    back:       ["track", "crack", "black", "pack", "attack", "lack", "stack"],
    know:       ["flow", "glow", "show", "grow", "below", "bestow", "outgrow"],
    show:       ["flow", "glow", "know", "grow", "below", "bestow", "outgrow"],
    flow:       ["know", "glow", "show", "grow", "below", "bestow", "outgrow"],
    fire:       ["desire", "inspire", "higher", "entire", "admire", "wire", "empire"],
    blood:      ["flood", "mud", "stud", "thud", "bud", "dud", "crud"],
    love:       ["above", "dove", "shove", "glove", "of", "enough", "tough"],
    soul:       ["whole", "role", "goal", "control", "console", "patrol", "enroll"],
    pain:       ["rain", "brain", "chain", "gain", "train", "insane", "remain"],
    rain:       ["pain", "brain", "chain", "gain", "train", "insane", "remain"],
    game:       ["name", "frame", "fame", "flame", "claim", "aim", "proclaim"],
    name:       ["game", "frame", "fame", "flame", "claim", "aim", "proclaim"],
    gold:       ["bold", "cold", "hold", "told", "fold", "unfold", "controlled"],
    world:      ["hurled", "swirled", "curled", "unfurled", "pearled", "twirled"],
    heart:      ["start", "apart", "smart", "chart", "dark", "spark", "embark"],
    dark:       ["spark", "heart", "start", "apart", "mark", "stark", "embark"],
    start:      ["heart", "apart", "smart", "chart", "dark", "spark", "embark"],
    deep:       ["sleep", "keep", "leap", "cheap", "sweep", "reap", "creep"],
    words:      ["birds", "herds", "nerds", "thirds", "chords", "lords", "swords"],
    never:      ["forever", "clever", "endeavor", "together", "whether", "fever"],
    forever:    ["never", "clever", "endeavor", "together", "whether", "fever"],
    dream:      ["scheme", "extreme", "stream", "team", "theme", "cream", "gleam"],
    rise:       ["wise", "prize", "skies", "ties", "disguise", "comprise", "size"],
    eyes:       ["rise", "wise", "skies", "ties", "disguise", "comprise", "size"],
    truth:      ["youth", "booth", "tooth", "sleuth", "uncouth", "proof", "roof"],
    made:       ["shade", "blade", "trade", "fade", "parade", "evade", "played"],
    said:       ["head", "dread", "spread", "ahead", "thread", "instead", "dead"],
    dead:       ["said", "head", "dread", "spread", "ahead", "thread", "instead"],
    head:       ["said", "dead", "dread", "spread", "ahead", "thread", "instead"],
    feel:       ["real", "deal", "steel", "heal", "reveal", "appeal", "conceal"],
    run:        ["done", "gun", "sun", "fun", "one", "none", "won"],
    done:       ["run", "gun", "sun", "fun", "one", "none", "won"],
    come:       ["some", "drum", "sum", "numb", "dumb", "overcome", "succumb"],
    some:       ["come", "drum", "sum", "numb", "dumb", "overcome", "succumb"],
    top:        ["drop", "stop", "pop", "shop", "crop", "hop", "nonstop"],
    drop:       ["top", "stop", "pop", "shop", "crop", "hop", "nonstop"],
    stop:       ["drop", "top", "pop", "shop", "crop", "hop", "nonstop"],
  };

  if (wordBank[w]) return wordBank[w].slice(0, 6);

  const suffixes: Array<[string, string[]]> = [
    ["ight", ["night", "fight", "right", "light", "might", "bright", "sight"]],
    ["ound", ["ground", "sound", "found", "bound", "round", "profound", "surround"]],
    ["ture", ["capture", "chapter", "laughter", "after", "rapture", "fracture"]],
    ["ipse", ["trips", "grips", "ships", "lips", "scripts", "crypts", "sips"]],
    ["ance", ["dance", "chance", "glance", "advance", "romance", "enhance"]],
    ["ence", ["dance", "chance", "glance", "advance", "fence", "hence", "dense"]],
    ["tion", ["vision", "mission", "position", "decision", "motion", "notion"]],
    ["sion", ["vision", "mission", "collision", "decision", "precision"]],
    ["ling", ["ring", "sing", "bring", "king", "spring", "swing", "sting"]],
    ["ting", ["ring", "sing", "bring", "king", "spring", "swing", "sting"]],
    ["ning", ["ring", "sing", "bring", "king", "spring", "swing", "sting"]],
    ["one",  ["bone", "stone", "alone", "tone", "phone", "zone", "clone"]],
    ["ame",  ["game", "flame", "name", "frame", "fame", "blame", "same"]],
    ["ack",  ["back", "track", "crack", "black", "pack", "attack", "lack"]],
    ["ine",  ["spine", "shine", "divine", "fine", "vine", "mine", "design"]],
    ["ire",  ["fire", "desire", "higher", "wire", "inspire", "entire", "empire"]],
    ["old",  ["cold", "bold", "gold", "hold", "told", "unfold", "controlled"]],
    ["end",  ["blend", "mend", "trend", "defend", "depend", "ascend", "transcend"]],
    ["ark",  ["dark", "spark", "heart", "start", "apart", "mark", "stark"]],
    ["art",  ["heart", "start", "apart", "smart", "chart", "spark", "dark"]],
    ["ide",  ["ride", "side", "guide", "pride", "hide", "divide", "inside"]],
    ["ake",  ["break", "shake", "wake", "stake", "mistake", "awake", "forsake"]],
    ["ain",  ["pain", "rain", "brain", "chain", "gain", "train", "insane"]],
    ["eel",  ["feel", "real", "deal", "steel", "heal", "reveal", "appeal"]],
    ["eal",  ["feel", "real", "deal", "steal", "heal", "reveal", "appeal"]],
    ["ust",  ["dust", "must", "gust", "adjust", "trust", "disgust", "just"]],
    ["oast", ["most", "coast", "toast", "host", "boast", "roast", "ghost", "post"]],
    ["ast",  ["last", "past", "vast", "fast", "blast", "contrast", "cast"]],
    ["ost",  ["most", "ghost", "coast", "toast", "boast", "host", "roast"]],
    ["ong",  ["strong", "song", "along", "wrong", "belong", "prolong", "beyond"]],
    ["ife",  ["life", "knife", "strife", "wife", "rife", "thrive"]],
    ["ile",  ["style", "mile", "smile", "file", "while", "denial", "trial"]],
    ["ace",  ["place", "space", "face", "grace", "trace", "embrace", "chase"]],
    ["ore",  ["more", "core", "floor", "soar", "explore", "restore", "implore"]],
    ["all",  ["fall", "call", "wall", "hall", "recall", "install", "enthrall"]],
    ["ool",  ["cool", "rule", "fool", "school", "tool", "fuel", "jewel"]],
    ["ope",  ["hope", "cope", "rope", "scope", "smoke", "spoke", "woke"]],
    ["eet",  ["street", "beat", "heat", "feat", "treat", "complete", "defeat"]],
    ["eat",  ["street", "beat", "heat", "feat", "treat", "complete", "defeat"]],
    ["age",  ["stage", "cage", "rage", "engage", "rampage", "barrage", "enrage"]],
    ["ox",   ["blocks", "rocks", "clocks", "knocks", "locks", "talks", "walks"]],
    ["ing",  ["ring", "sing", "bring", "king", "spring", "swing", "sting"]],
    ["ize",  ["rise", "wise", "prize", "skies", "ties", "disguise", "comprise"]],
    ["llow", ["follow", "swallow", "shallow", "mellow", "yellow", "fellow", "bellow"]],
    ["rrow", ["borrow", "sorrow", "narrow", "arrow", "sparrow", "marrow", "barrow"]],
    ["ow",   ["flow", "glow", "know", "show", "grow", "below", "bestow", "outgrow"]],
    ["ay",   ["way", "stay", "play", "say", "pray", "display", "today"]],
    ["aw",   ["raw", "saw", "draw", "flaw", "law", "jaw", "awe"]],
    ["oo",   ["true", "blue", "through", "crew", "pursue", "debut", "renew"]],
    ["ew",   ["true", "blue", "through", "crew", "pursue", "debut", "renew"]],
    ["ee",   ["free", "see", "key", "tree", "degree", "agree", "emcee"]],
    ["on",   ["gone", "con", "spawn", "beyond", "upon", "respond", "drawn"]],
    ["om",   ["phantom", "random", "rhythm", "kingdom", "ransom", "bottom", "wisdom"]],
  ];

  for (let len = 4; len >= 2; len--) {
    const suffix = w.slice(-len);
    const entry = suffixes.find(([s]) => s === suffix);
    if (entry) return entry[1].filter((r) => r !== w).slice(0, 6);
  }

  const tail = w.slice(-3);
  const tail3: Record<string, string[]> = {
    ack: ["back", "track", "crack", "black", "attack"],
    ame: ["game", "flame", "name", "frame", "same"],
    are: ["dare", "care", "share", "there", "where"],
    ark: ["dark", "spark", "mark", "start", "heart"],
    art: ["heart", "start", "smart", "chart", "apart"],
    ast: ["last", "past", "fast", "blast", "contrast"],
    ate: ["late", "fate", "state", "great", "wait"],
    ave: ["save", "brave", "wave", "grave", "cave"],
    aze: ["blaze", "gaze", "phase", "raise", "days"],
    ear: ["fear", "near", "clear", "here", "appear"],
    eed: ["need", "feed", "greed", "speed", "freed"],
    ell: ["tell", "sell", "well", "spell", "fell"],
    end: ["blend", "mend", "trend", "defend", "ascend"],
    ent: ["bent", "sent", "went", "spent", "rent"],
    ess: ["stress", "bless", "press", "mess", "confess"],
    est: ["best", "rest", "chest", "test", "west"],
    ide: ["ride", "side", "guide", "pride", "hide"],
    ill: ["still", "fill", "will", "skill", "kill"],
    ind: ["mind", "find", "kind", "blind", "grind"],
    ing: ["ring", "sing", "bring", "king", "spring"],
    ink: ["think", "drink", "link", "sink", "blink"],
    ire: ["fire", "desire", "wire", "inspire", "entire"],
    ist: ["twist", "fist", "list", "mist", "resist"],
    ive: ["live", "give", "strive", "drive", "thrive"],
    ock: ["block", "rock", "clock", "knock", "lock"],
    ole: ["soul", "role", "whole", "goal", "control"],
    ome: ["home", "roam", "dome", "foam", "chrome"],
    one: ["bone", "alone", "stone", "tone", "phone"],
    ong: ["strong", "song", "along", "wrong", "belong"],
    oom: ["room", "bloom", "doom", "zoom", "loom"],
    ore: ["more", "core", "floor", "soar", "explore"],
    orn: ["born", "torn", "worn", "corn", "sworn"],
    ost: ["most", "ghost", "coast", "toast", "boast"],
    oud: ["crowd", "loud", "proud", "cloud", "shroud"],
    own: ["crown", "town", "down", "brown", "grown"],
    ump: ["jump", "dump", "pump", "bump", "stump"],
    unk: ["drunk", "funk", "chunk", "trunk", "junk"],
    urn: ["burn", "turn", "learn", "earn", "return"],
    ust: ["dust", "must", "gust", "trust", "disgust"],
  };
  if (tail3[tail]) return tail3[tail].filter((r) => r !== w).slice(0, 6);

  return ["fire", "night", "rain", "soul"].filter((r) => r !== w);
}

/**
 * Bidirectional rhyme validation.
 * Returns true only if `rhyme` appears in suggestRhymes(word) OR
 * `word` appears in suggestRhymes(rhyme). Using both directions means
 * suffix-matching false positives (e.g. "roast"→"ast"→"last") are caught
 * because the reverse lookup ("last"→suggestRhymes→no "roast") fails too.
 */
export function isValidRhymePair(word: string, rhyme: string): boolean {
  const w = word.toLowerCase().replace(/[^a-z]/g, "");
  const r = rhyme.toLowerCase().replace(/[^a-z]/g, "");
  if (!w || !r || w === r) return false;
  if (suggestRhymes(w).includes(r)) return true;
  if (suggestRhymes(r).includes(w)) return true;
  return false;
}
