const colors = {
  light: {
    background: "#0A0A0F",
    surface: "#13131C",
    card: "#1C1C2A",
    text: "#FFFFFF",
    textMuted: "#8B8FA8",
    foreground: "#FFFFFF",
    cardForeground: "#FFFFFF",
    primary: "#F5C518",
    primaryForeground: "#0A0A0F",
    secondary: "#1C1C2A",
    secondaryForeground: "#FFFFFF",
    accent: "#F5C518",
    accentForeground: "#0A0A0F",
    violet: "#9B5DE5",
    cyan: "#00F5D4",
    red: "#FF4D6D",
    radarGrid: "#FFFFFF18",
    radarGridStrong: "#FFFFFF28",
    muted: "#1C1C2A",
    mutedForeground: "#8B8FA8",
    border: "#2A2A3C",
    input: "#1C1C2A",
    destructive: "#FF4D6D",
    destructiveForeground: "#FFFFFF",
    tint: "#F5C518",
    courtBackdrop: "#160F19",
  },
  dark: {
    background: "#0A0A0F",
    surface: "#13131C",
    card: "#1C1C2A",
    text: "#FFFFFF",
    textMuted: "#8B8FA8",
    foreground: "#FFFFFF",
    cardForeground: "#FFFFFF",
    primary: "#F5C518",
    primaryForeground: "#0A0A0F",
    secondary: "#1C1C2A",
    secondaryForeground: "#FFFFFF",
    accent: "#F5C518",
    accentForeground: "#0A0A0F",
    violet: "#9B5DE5",
    cyan: "#00F5D4",
    red: "#FF4D6D",
    radarGrid: "#FFFFFF18",
    radarGridStrong: "#FFFFFF28",
    muted: "#1C1C2A",
    mutedForeground: "#8B8FA8",
    border: "#2A2A3C",
    input: "#1C1C2A",
    destructive: "#FF4D6D",
    destructiveForeground: "#FFFFFF",
    tint: "#F5C518",
    courtBackdrop: "#160F19",
  },
  radius: 12,
};

export default colors;
